name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  build:
    name: Test
    strategy:
      matrix:
        scala:
          - 2.13.6
        java:
          - adopt@1.11
          - adopt@1.15
        os:
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install Java And Sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cache/coursier
            $HOME/.ivy2/cache
            $HOME/.sbt/boot/
            $HOME/.sbt
            lib_managed
            target
            project/target
          key: ${{ runner.os }}-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Test (${{ matrix.scala }}, ${{ matrix.java }})
        run: sbt ++${{ matrix.scala }} fullTest
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
